export const AUDIT_ACTION_LABELS: Record<string, string> = {
  'payment.approve': 'Pago aprobado',
  'payment.reject': 'Pago rechazado',
  'membership.assign': 'Membresía asignada',
  'membership.create': 'Plan creado',
  'membership.update': 'Plan actualizado',
  'membership.delete': 'Membresía eliminada',
  'user.status_change': 'Estado de usuario',
  'user.role_change': 'Cambio de rol',
  'user.delete': 'Usuario eliminado',
  'user.create': 'Usuario creado',
  'user.profile_update': 'Perfil actualizado',
  'trainer.create': 'Entrenador creado',
  'trainer.profile_update': 'Perfil entrenador',
  equipment_create: 'Equipo creado',
  equipment_delete: 'Equipo eliminado',
  equipment_retire: 'Equipo retirado',
  equipment_zone_create: 'Zona creada',
  'report.export': 'Exportación CSV',
  'admin.bootstrap': 'Bootstrap admin',
  'reception.check_in': 'Entrada recepción',
  'reception.check_out': 'Salida recepción',
  'reception.walk_in': 'Registro walk-in',
  'settings.expiry.update': 'Config. vencimientos',
  'settings.expiry.run': 'Job vencimientos',
  'settings.exchange_rate.override': 'Override tasa BCV',
  'settings.exchange_rate.clear_override': 'Quitar override BCV',
  'settings.exchange_rate.refresh': 'Refresh tasa BCV',
  'exchange_rate.refresh': 'Refresh tasa BCV',
  'auth.login': 'Inicio de sesión',
  'auth.logout': 'Cierre de sesión',
  'auth.register': 'Registro',
  'auth.change_password': 'Cambio contraseña',
  'auth.mfa.enabled': 'MFA activado',
  'auth.mfa.disabled': 'MFA desactivado',
  'auth.mfa.setup_started': 'MFA configuración',
  'auth.mfa_login_failed': 'MFA fallido',
};

export function auditActionLabel(action: string): string {
  return AUDIT_ACTION_LABELS[action] ?? action.replace(/\./g, ' · ');
}
